name: "Build Firefox"

on:
    push:
        branches:
            - "release"
    pull_request:
        branches:
            - "release"

env:
    SCCACHE_VERSION: "0.5.4"
    DEPS_CACHE: |
      ~/.mozbuild
      /usr/local/bin/sccache

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout source tree
              uses: actions/checkout@v3

            - name: Restore dependency cache
              id: deps-cache
              uses: actions/cache/restore@v3
              with:
                path: ${{ env.DEPS_CACHE }}
                key: deps-${{ runner.os }}

            - name: Install dependencies
              run: |
                sudo apt-get install -y curl \
                                   python3 \
                                   python3-pip

                if [ ! -f "/usr/local/bin/sccache" ]; then
                  curl -L https://github.com/mozilla/sccache/releases/download/v${{ env.SCCACHE_VERSION }}/sccache-v${{ env.SCCACHE_VERSION }}-$(uname -m)-unknown-linux-musl.tar.gz | tar -xzf -
                  sudo mv sccache-v${{ env.SCCACHE_VERSION }}-$(uname -m)-unknown-linux-musl/sccache /usr/local/bin/
                fi

                ./mach --no-interactive bootstrap --application-choice browser

            - name: Cache dependencies
              uses: actions/cache/save@v3
              with:
                path: ${{ env.DEPS_CACHE }}
                key: ${{ steps.deps-cache.outputs.cache-primary-key }}
  

            - name: Configure the build
              run: |
                touch mozconfig
                # todo: work out why we can't build without this
                echo "ac_add_options --without-wasm-sandboxed-libraries" >> mozconfig
                echo "ac_add_options --with-ccache=sccache" >> mozconfig

            - name: Build the source tree
              run: |
                echo "Compilation started at $(date '+%a %d %b %Y %H:%M:%S %Z')."
                ./mach build
